-- Create Database
CREATE DATABASE IF NOT EXISTS HACKATHON_IOT;

USE DATABASE HACKATHON_IOT;

-- Create Schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CLEAN;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- Create Raw IoT Events Table
CREATE OR REPLACE TABLE RAW.IOT_EVENTS (
    id INT,
    device_id STRING,
    latitude FLOAT,
    longitude FLOAT,
    event_timestamp TIMESTAMP_NTZ,
    op STRING,
    raw_payload VARIANT,
    loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- View Raw Data
SELECT * FROM RAW.IOT_EVENTS;

-- View Bronze Layer
SELECT * FROM RAW.IOT_EVENTS_BRONZE;

-- View Silver Layer
SELECT * FROM CLEAN.IOT_EVENTS_SILVER;

-- View Gold Layer
SELECT * FROM ANALYTICS.IOT_EVENTS_GOLD;